---
# yamllint disable-line rule:line-length
exclude_dirs:
  [
    "hooks/tests/",
    "tests",
    "static",
    "templates",
    ".eggs",
    ".tox",
    ".venv",
    ".direnv",
    "megalinter-reports",
  ]

skips: ["B101", "B404", "B607", "B603"]
