extends: default
rules:
  new-lines:
    level: warning
    type: unix
  line-length:
    max: 500
  document-start:
    present: false
  comments:
    min-spaces-from-content: 1 # Used to follow prettier standard: https://github.com/prettier/prettier/pull/10926
