name: test-specific

on:
  workflow_dispatch:
    inputs:
      expression:
        description: "Test expression to filter for"
        required: true
        type: choice
        options:
          - "uv-none-mkdocs"
          - "uv-none-none"
          - "uv-requirements.txt-mkdocs"
          - "uv-requirements.txt-none"
          - "virtualenv-requirements.txt-mkdocs"
          - "virtualenv-requirements.txt-none"
          - "conda-requirements.txt-mkdocs"
          - "conda-requirements.txt-none"
          - "conda-environment.yml-mkdocs"
          - "conda-environment.yml-none"
          - "pipenv-Pipfile-mkdocs"
          - "pipenv-Pipfile-none"
          - "none-requirements.txt-mkdocs"
          - "none-requirements.txt-none"
      os:
        description: "Operating system to run on"
        required: true
        type: choice
        default: "ubuntu-latest"
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest

jobs:
  tests-specific:
    name: Tests (${{ inputs.os }})
    runs-on: ${{ inputs.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          allow-prereleases: true
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            dev-requirements.txt

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Cache conda packages
        uses: actions/cache@v4
        env:
          # Increase this value to reset cache explicitly
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('ccds/hook_utils/dependencies.py') }}

      - name: Setup for Windows
        if: ${{ inputs.os == 'windows-latest' }}
        run: |
          # Install GNU make
          choco install --verbose make
          # Add conda binaries directory to PATH so that conda is accessible
          echo "${CONDA}\Scripts" >> $GITHUB_PATH
          # Set bash executable explicitly since Make may pick wrong shell
          echo "BASH_EXECUTABLE=$(which bash)" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make requirements

      - name: Check dependencies
        run: |
          if [[ -z "${BASH_EXECUTABLE}" ]]; then
            bash --version
          else
            echo $BASH_EXECUTABLE
            $BASH_EXECUTABLE --version
          fi
          which make
          make --version
          which conda
          conda --version
          which pipenv
          pipenv --version
          which virtualenv
          virtualenv --version

      - name: Run tests
        run: |
          make test ARGS="-k ${{ inputs.expression }}"
